### ISSUE TITLE
Rewardtable.mbin Error in 2.0.4.1

### ISSUE THREAD

**Issue by RealMiith** [monkeyman192/MBINCompiler#120]
[VERSION]: MBINCompiler v2.0.4.1
[ARGS]: "C:\Users\Miithos\Desktop\NO MANS SKY MODDING\oRIGINAL\METADATA\REALITY\TABLES\REWARDTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcRewardTable from MBIN.
[DeserializeTemplateException]: Failed to deserialize template ,!

   at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by RealMiith** [comment]
sorry did not read that this was  not functioning yet.

**Comment by monkeyman192** [comment]
yeah, this file will take a while since there are so many rewards. Same with the cost table etc
