### ISSUE TITLE
MBINCompiler process hangs on attempted decompile, unspecific errors in log

### ISSUE THREAD

**Issue by RandomOfAmber** [monkeyman192/MBINCompiler#130]
I have had this issue the past few days, and on several different globals I have tried decompiling. Issue recurs both within NMS Modding Station and trying to use the MBINCompiler directly, outside NMSMS. I am attempting to use latest release of the compiler and .dll (v2.09-pre1).

MOST of these globals kick up the following in the error log:

> [WARN]: File not recognized. You may need to use an older version of MBINCompiler.
>   [INFO]: G:\NMS Finished Mods Folder\TorchTest\GCUIGLOBALS.GLOBAL.MBIN
>   [INFO]: MBIN	version:	0.0.0.0	guid:	B0A618899754E7E2	template:	cGcUIGlobals
>   
> 
> [ERROR]: [AggregateException]: One or more errors occurred.

The problem occurs (at least) on the following files:
GCGALAXYGLOBALS
GCUIGLOBALS
GCGAMEPLAYGLOBALS (log only displays "[ERROR]: [AggregateException]: One or more errors occurred.")
GCCREATUREGLOBALS

Let me know if I can provide any other useful information. Thanks!

**Comment by RandomOfAmber** [comment]
Reading through the docs it seemspossible that I am the one in error here, and not MBINCompiler. Will update this issue, and/or delete it, as I explore the matter in greater detail... (Apologies if I've thrown this up over nothing!)

EDIT: Hmm, no, I don't think the problem is me. I tried running the compiler through command line and tried to force the convert on GCGAMEPLAYGLOBALS (as an example), and ended up with the following:

`[ERROR]: [MbinException]: Failed serializing GcGameplayGlobals to EXML.
  [InvalidOperationException]: There was an error generating the XML document.
  [ArgumentException]: '', hexadecimal value 0x06, is an invalid character.
  
  [INFO]: E:\Downloaded Stuff\No Man's Sky Mods, Etc\NMS Modding 2019\NMS Modding Station 1.2.2-320-1-2-2\gcgameplayglobals.global.mbin
  [INFO]: MBIN	version:	0.0.0.0	guid:	397E231F547EC919	template:	cGcGameplayGlobals
  
     at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
     at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
     at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
     at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
     at System.Xml.XmlWellFormedWriter.WriteString(String text)
     at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed serializing GcGameplayGlobals to EXML.`

**Comment by monkeyman192** [comment]
I haven't yet updated MBINCompiler to support these particular globals.
With Beyond globals became a lot harder to map out so they take a lot longer than before.
See #119 to see the progress on updating files.
I'll close this but I will try update the information on submitting issues to include a message to indicate that if you are having issues with a particular struct to have a look at the open issues to see if the struct is meant to supported after a recent update!
