### ISSUE TITLE
GCGAMEPLAYGLOBALS.GLOBAL.MBIN still broken?

### ISSUE THREAD

**Issue by cokkto** [monkeyman192/MBINCompiler#219]
```
[VERSION]: MBINCompiler v2.31.0.2
[ARGS]: "convert" ".\GCGAMEPLAYGLOBALS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: C:\NMSmodingStation\projects\default\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	D63C573635B92376	template:	cGcGameplayGlobals
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed serializing GcGameplayGlobals to EXML.
[InvalidOperationException]: There was an error generating the XML document.
[ArgumentException]: '', hexadecimal value 0x01, is an invalid character.

   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)
```

**Comment by monkeyman192** [comment]
This file hasn't yet been updated. Please see #215 with info about which file have or haven't been updated.

**Comment by cokkto** [comment]
oh, sorry, didn't notece "except" word, thought these listed were fixed

**Comment by monkeyman192** [comment]
Nope, only the ones ticked off :)

**Comment by SirOutlander** [comment]
In v2.32.0-pre1 GCGAMEPLAYGLOBALS.GLOBAL.MBIN is strikethrough does this mean it will not be upported?

>[INFO]:   Found in NMSARC.59B126E2.pak: GCGAMEPLAYGLOBALS.GLOBAL.MBIN
[INFO]: Getting GCGAMEPLAYGLOBALS.GLOBAL.EXML from NMS source PAKs
[INFO]: Trying to decompile... 
    [WARNING]: MBINCompiler = [[WARN]: File not recognized. You may need to use an older version of MBINCompiler. OR check your script!]
    [WARN]:    MBINCompiler =   [[INFO]: GCGAMEPLAYGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	D63C573635B92376	template:	cGcGameplayGlobals]
    [WARN]:    MBINCompiler = [[ERROR]: [MbinException]: Failed to read GcGameplayGlobals from MBIN.]

**Comment by monkeyman192** [comment]
Yes. We make no attempt to ensure any kind of compatibility for any version other than the latest unfortunately.
I use the strikethrough to indicate that there is a newer version in an update list so that I don't map structs twice.
It's much too much effort to map it perfectly for every single release as the bar moves so regularly I can barely get one list finished before HG makes more changes lol
