### ISSUE TITLE
An EXML exception has occured?

### ISSUE THREAD

**Issue by I-tiger** [monkeyman192/MBINCompiler#266]
[VERSION]: MBINCompiler v2.51.0.1
[ARGS]: "convert" "-y" "-f" "C:\Users\crabh\Desktop\UnlimitedShipHyperdriveRange.2.1.zip-918-2-1-1590425873\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.EXML"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=EXML
[INFO]: --input-format=EXML --output-format=MBIN

[ERROR]: [ExmlException]: An EXML exception has occurred!
  [OverflowException]: Value was either too large or too small for a Single.

[INFO]: C:\Users\crabh\Desktop\UnlimitedShipHyperdriveRange.2.1.zip-918-2-1-1590425873\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.EXML
  
     at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
     at libMBIN.NMSTemplate.DeserializeEXmlValue(NMSTemplate template, Type fieldType, FieldInfo field, EXmlProperty xmlProperty, Type templateType, NMSAttribute settings)
     at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
     at libMBIN.NMSTemplate.DeserializeEXmlValue(NMSTemplate template, Type fieldType, FieldInfo field, EXmlProperty xmlProperty, Type templateType, NMSAttribute settings)
     at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
     at libMBIN.NMSTemplate.DeserializeEXmlValue(NMSTemplate template, Type fieldType, FieldInfo field, EXmlProperty xmlProperty, Type templateType, NMSAttribute settings)
     at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
     at libMBIN.EXmlFile.ReadTemplateFromXmlReader(XmlReader reader, String& templateName)
     at libMBIN.EXmlFile.ReadTemplateFromStream(Stream input, String& templateName)
     at MBINCompiler.Commands.Convert.ConvertEXML(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: An EXML exception has occurred!
  [FILE]: C:\Users\crabh\Desktop\UnlimitedShipHyperdriveRange.2.1.zip-918-2-1-1590425873\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.EXML
  
[INFO]: TIME: 0.094 seconds
_____________________________________
This is the fourth time this happened. what is going on?!

**Comment by monkeyman192** [comment]
Sorry for the long delay... Can you please upload the file you are having issues with?

**Comment by monkeyman192** [comment]
I'm going to close this as the tests all pass and the game has been subsequently updated....
