### ISSUE TITLE
GCPLAYERGLOBALS.GLOBAL.MBIN unsuccessful decompile to EXML

### ISSUE THREAD

**Issue by laanp** [monkeyman192/MBINCompiler#307]
[VERSION]: MBINCompiler v3.34.0.1
[ARGS]: "convert" "-y" "-f" "D:\NMS Modding\My Mods\Pete\GCPLAYERGLOBALS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: D:\NMS Modding\My Mods\Pete\GCPLAYERGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	E1FF6D5955EA6F71	template:	cGcPlayerGlobals
  [EXPECTED INFO]: GUID: 6A8A84FDBD56764A
  
  [WARN]: The defined Size for MuzzleFlashScale does not match the length of libMBIN.NMS.GameComponents.GcPlayerWeapons+WeaponModeEnum!
  13 != 15
  This is NOT an issue with your MBIN or EXML file and can be ignored.
  If you are seeing this message however, please report it.
  [WARN]: The defined Size for WeaponVibrationIDs does not match the length of libMBIN.NMS.GameComponents.GcPlayerWeapons+WeaponModeEnum!
  13 != 15
  This is NOT an issue with your MBIN or EXML file and can be ignored.
  If you are seeing this message however, please report it.
  [WARN]: The defined Size for WeaponShakeIDs does not match the length of libMBIN.NMS.GameComponents.GcPlayerWeapons+WeaponModeEnum!
  13 != 15
  This is NOT an issue with your MBIN or EXML file and can be ignored.
  If you are seeing this message however, please report it.
  [WARN]: The defined Size for WeaponVibrationScales does not match the length of libMBIN.NMS.GameComponents.GcPlayerWeapons+WeaponModeEnum!
  13 != 15
  This is NOT an issue with your MBIN or EXML file and can be ignored.
  If you are seeing this message however, please report it.

[ERROR]: [MbinException]: Failed serializing GcPlayerGlobals to EXML.
  [InvalidOperationException]: There was an error generating the XML document.
  [ArgumentException]: '', hexadecimal value 0x03, is an invalid character.
  
  [INFO]: D:\NMS Modding\My Mods\Pete\GCPLAYERGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	E1FF6D5955EA6F71	template:	cGcPlayerGlobals
  
     at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
     at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
     at System.Xml.XmlWellFormedWriter.WriteString(String text)
     at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed serializing GcPlayerGlobals to EXML.
  [FILE]: D:\NMS Modding\My Mods\Pete\GCPLAYERGLOBALS.GLOBAL.MBIN
  
[INFO]: 1 WARNINGS.

  [WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [FILE]: D:\NMS Modding\My Mods\Pete\GCPLAYERGLOBALS.GLOBAL.MBIN
  
[INFO]: TIME: 0.062 seconds

**Comment by monkeyman192** [comment]
See https://github.com/monkeyman192/MBINCompiler/issues/303. This file isn't yet supported.
Also, please read the contents of the issue before raising one. We don't need reports when we already know these files are not yet supported
