### ISSUE TITLE
GCVEHICLEGLOBALS.GLOBAL.MBIN failed to decompile

### ISSUE THREAD

**Issue by gobi42** [monkeyman192/MBINCompiler#308]
[VERSION]: MBINCompiler v3.34.0.1
[ARGS]: "D:\games\Mods\MbinCompiler\GCVEHICLEGLOBALS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed serializing GcVehicleGlobals to EXML.
[InvalidOperationException]: There was an error generating the XML document.
[ArgumentException]: '', hexadecimal value 0x19, is an invalid character.

   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)

**Comment by monkeyman192** [comment]
See https://github.com/monkeyman192/MBINCompiler/issues/303. This file isn't yet supported.
Also, please read the contents of the issue before raising one. We don't need reports when we already know these files are not yet supported
