### ISSUE TITLE
PLAYERSPAWNOUT.ANIM.MBIN

### ISSUE THREAD

**Issue by ianm32** [monkeyman192/MBINCompiler#33]
MODELS\EFFECTS\PLAYER\ANIMS\PLAYERSPAWNOUT.ANIM.MBIN does not decompile. Error message is:

`Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.MBINFile.GetData()
   at MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   at MBINCompiler.Program.Main(String[] args)`

**Comment by monkeyman192** [comment]
Ok so the issue is https://github.com/monkeyman192/MBINCompiler/blob/development/libMBIN/Source/Models/Structs/TkAnimNodeFrameData.cs#L7
It is not a list of something that is 2 bytes long. I would have guessed a half-float but it doesn't look quite right...

**Comment by honestleaf** [comment]
Got a similar issue on \METADATA\REALITY\TABLES\NMS_REALITY_GCPROCPRODUCTTABLE.MBIN. Here is the output:
Values index out of Range. Struct: libMBIN.Models.Structs.GcRealitySubstanceCategory field: SubstanceCategory
ERROR: An unknown exception occurred!
调用的目标发生了异常。
Stacktrace:
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   在 libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   在 libMBIN.MBINFile.GetData()
   在 MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   在 MBINCompiler.Program.Main(String[] args)

**Comment by monkeyman192** [comment]
@honestleaf So there is a slight issue with this file in that I do not believe that it is actually used by the game.
The struct in it is a kind of old version of the current one. I tried to decompile this file before realising that this table is actually not used and it is in fact the PROCEDURALPRODUCTTABLE.MBIN which controls the procedural products. It is possible to construct a struct that will allow this file to be decompiled, however it may not work automatically as both this old file and the proper one have the same struct name.

**Comment by honestleaf** [comment]
I was trying to figure out the "refine" table when I encountered this issue. According to your find, this file doesn't contain useful data. Maybe it is not worth to be decompiled.

**Comment by monkeyman192** [comment]
I believe this has been resolved
