### ISSUE TITLE
Some additional information in error reporting.

### ISSUE THREAD

**Issue by Babscoole** [monkeyman192/MBINCompiler#336]
When a property name is incorrect, the error output would be something like:

[ERROR]: [AggregateException]: One or more errors occurred.
[ExmlException]: An EXML exception has occurred!
[NullReferenceException]: Object reference not set to an instance of an object.

   at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   at libMBIN.NMSTemplate.DeserializeEXmlValue(NMSTemplate template, Type fieldType, FieldInfo field, EXmlProperty xmlProperty, Type templateType, NMSAttribute settings)
   at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   at libMBIN.EXmlFile.ReadTemplateFromXmlReader(XmlReader reader, String& templateName)
   at libMBIN.EXmlFile.ReadTemplateFromStream(Stream input, String& templateName)
   at MBINCompiler.Commands.Convert.ConvertEXML(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)

Would be helpful for debugging if the error report could include the field name(s) causing the error(s).

Thanks.

**Comment by Babscoole** [comment]
Bump.  :)  I think one bump in 10 month is ok
