### ISSUE TITLE
PLANTINTERACTION.ENTITY.exml

### ISSUE THREAD

**Issue by jacobericson** [monkeyman192/MBINCompiler#34]
PLANTINTERACTION.ENTITY.exml does not recompile

Index must be within the bounds of the List.
Parameter name: index
Stacktrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at libMBIN.Models.NMSTemplate.SerializeValue(BinaryWriter writer, Type fieldType, Object fieldData, NMSAttribute settings, FieldInfo field, List`1& additionalData, Int32& addtDataIndex, Int32 structLength, UInt32 listEnding)
   at libMBIN.Models.NMSTemplate.AppendToWriter(BinaryWriter writer, List`1& additionalData, Int32& addtDataIndex, Type parent, UInt32 listEnding)
   at libMBIN.Models.NMSTemplate.SerializeGenericList(BinaryWriter writer, IList list, Int64 listHeaderPosition, List`1& additionalData, Int32 addtDataIndex, UInt32 listEnding)
   at libMBIN.Models.NMSTemplate.SerializeBytes()
   at libMBIN.MBINFile.SetData(NMSTemplate template)
   at MBINCompiler.Program.CompileFile(String inputPath, String outputPath)
   at MBINCompiler.Program.Main(String[] args)

**Comment by monkeyman192** [comment]
This is fixed in [1.53.0-pre2](https://github.com/monkeyman192/MBINCompiler/tree/1.53.0-pre2)
