### ISSUE TITLE
PROJECTILETABLE.MBIN failed to decompile, No Mans Sky Version 3.85, Expedition 6

### ISSUE THREAD

**Issue by BradfordCB** [monkeyman192/MBINCompiler#452]
[VERSION]: MBINCompiler v3.84.0.2
[ARGS]: "convert" "-y" "-f" "T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML
[INFO]: T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN

[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [INFO]: T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	B746274856D45F1B	template:	cGcProjectileDataTable
  [EXPECTED INFO]: GUID: 1053F5FF51AB5D94
  

[ERROR]: [MbinException]: There was an error generating the XML document.
  [InvalidOperationException]
  [ArgumentException]: '', hexadecimal value 0x06, is an invalid character.
  
  [INFO]: T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	B746274856D45F1B	template:	cGcProjectileDataTable
  
     at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
     at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
     at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
     at System.Xml.XmlWellFormedWriter.WriteString(String text)
     at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed serializing GcProjectileDataTable to EXML.
  [FILE]: T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN
  
[INFO]: 1 WARNINGS.

  [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [FILE]: T:\BCB.NMS.Mods\A-WeaponsMod04\METADATA\PROJECTILES\PROJECTILETABLE.MBIN
  
[INFO]: TIME: 0.093 seconds

**Comment by Babscoole** [comment]
Not a bug, MBINCompiler hadn't been updated for Outlaws compatibility yet.  Partial update posted a few hours ago.

**Comment by BradfordCB** [comment]
Thankyou
