### ISSUE TITLE
Exception when parsing NMS_TESTREALITY_GCSUBSTANCETABLE.MBIN

### ISSUE THREAD

**Issue by DoctorVanGogh** [monkeyman192/MBINCompiler#46]
```
Values index out of Range. Struct: libMBIN.Models.Structs.GcRealitySubstanceCategory field: SubstanceCategory
ERROR: An unknown exception occurred!
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent) in [Foo]\MBINCompiler\libMBIN\Source\Models\NMSTemplate.cs:line 118
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName) in [Foo]\MBINCompiler\libMBIN\Source\Models\NMSTemplate.cs:line 200
   at libMBIN.MBINFile.GetData() in [Foo]\MBINCompiler\libMBIN\Source\MBINFile.cs:line 71
   at MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose) in [Foo]\MBINCompiler\MBINCompiler\Program.cs:line 49
   at MBINCompiler.Program.Main(String[] args) in [Foo]\MBINCompiler\MBINCompiler\Program.cs:line 335
```

Link to [mbin file](https://drive.google.com/open?id=1RzKJmJ0hlUGZKdQ1n-Lgf54NPGRAepJx) since github won't accept it as inline attachment :(

**Comment by monkeyman192** [comment]
I believe that the TESTREALITY files are old ones or unused ones?
Can you check and see whether or not the normal GCSUBSTANCETABLE file decompiles with the current version (it may be broken also... Haven't checked yet)
If not, then there isn't much I can do as HG seems to be leaving some of these legacy files around and they can't be decompiled with the current structs. It is also not really possible to create two versions of the struct just to read a file that won't be used...

**Comment by DoctorVanGogh** [comment]
Both `NMS_REALITY_GCSUBSTANCETABLE` & `NMS_U3REALITY_GCSUBSTANCETABLE` decompile just fine.

I was specifically going after `TESTREALITY` because it had one of the very few references to some (legacy?) materials not defined other files. But the raw `mbin` wasn't really helpful here 😞 

I'd argue that surely those files must be version tagged _somehow_ and that could be used as a discriminator, but I also realize that ~~spending~~ wasting time on legacy and orphaned files might not be well spent 😉

**Comment by monkeyman192** [comment]
It also hard as the struct can be an intermediate one that is somewhere between 1.38 and 1.50, so it isn't always possible to even read the actual struct from the exe. I did this for one of the proc product tables before realising that there are two and one must be an older version which is still there for some reason.
I'll close this if that's fine. Let me know if there is an issue and I need to re-open it.
