### ISSUE TITLE
Decompile Error: GCCAMERAGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by Muji-k** [monkeyman192/MBINCompiler#50]
I'm receiving the following error when i try to decrypt the GCCAMERAGLOBALS.GLOBAL.MBIN file from the latest build (1.55 - 3020240) after I extracted it from the NMSARC.59B126E2.pak file with the latest PSArcTool 

```Values index out of Range. Struct: libMBIN.Models.Structs.TkCurveType field: Curve
ERROR: An unknown exception occurred!
Error
Stacktrace:
   at libMBIN.Models.NMSTemplate.FinishDeserialize()
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.MBINFile.GetData()
   at MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   at MBINCompiler.Program.Main(String[] args)
```
The decryption was working just fine with the 1.53.0-pre4 release, but with the 1.55.0-pre1 release it throws the aforementioned error.

**Comment by monkeyman192** [comment]
This has been fixed in the latest release
