### ISSUE TITLE
NMS_REALITY_GCPROCPRODUCTTABLE.MBIN: unknown exception

### ISSUE THREAD

**Issue by VulcanTourist** [monkeyman192/MBINCompiler#59]
While performing a mass decryption(?) of all the .MBIN files, this occurred:

>mbincompiler.exe ".\METADATA\REALITY\TABLES\NMS_REALITY_GCPROCPRODUCTTABLE.MBIN"
```
ERROR: An unknown exception occurred!
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.MBINFile.GetData()
   at MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   at MBINCompiler.Program.Main(String[] args)
```
There were a number of failures during the very long process, but that one caught my eye.

**Comment by monkeyman192** [comment]
This is the same file we do not expect to decompile. I need to make some kind of announcement or something to indicate the files that we do not care about...

**Comment by Catsbuggy** [comment]
@monkeyman192 please yes, because i have some files i try to decompilate with same trouble.
a list with the file that you do not want or that are not yet possible to decompile would be very useful for your users and for our bug reports 

Thanks in advance :)
