### ISSUE TITLE
omiting VariableSizeString Linked property in LinkableNMSTemplate throws an error instead of re-adding a default value.

### ISSUE THREAD

**Issue by roie-r** [monkeyman192/MBINCompiler#612]
I noticed a minor oddity with the new `LinkableNMSTemplate` class (present in `TkAttachmentData > Components`)
If you omit `Linked` property, instead of re-adding it with a default value like other string properties elsewhere, the process throws an error... it's different behavior from other properties.

ERR INFO:    at libMBIN.NMSTemplate.SerializeValue(BinaryWriter writer, Type fieldType, Object fieldData, NMSAttribute settings, FieldInfo field, List`1& additionalData, Int32& addtDataIndex, UInt32 listEnding, Byte paddingByte)
   at libMBIN.NMSTemplate.AppendToWriter(BinaryWriter writer, List`1& additionalData, Int32& addtDataIndex, Type parent, UInt32 listEnding, Byte paddingByte)
   at libMBIN.NMSTemplate.SerializeValue(BinaryWriter writer, Type fieldType, Object fieldData, NMSAttribute settings, FieldInfo field, List`1& additionalData, Int32& addtDataIndex, UInt32 listEnding, Byte paddingByte)
   at libMBIN.NMSTemplate.SerializeList(BinaryWriter writer, IList list, Int64 listHeaderPosition, List`1& additionalData, Int32 addtDataIndex, UInt32 listEnding, Byte paddingByte, Boolean writingHashMap)
   at libMBIN.NMSTemplate.SerializeBytes()
   at libMBIN.MBINFile.SetData(NMSTemplate template)
   at MBINCompiler.Commands.Convert.ConvertEXML(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)

**Comment by monkeyman192** [comment]
Damn... I completely missed this issue... Sorry!
I'm hoping this is no longer the case with what will be the latest version coming out tomorrow, but if you are still around and could test once it's out that would be great

**Comment by roie-r** [comment]
The new mxml format moved the link to the class header attributes - so this issue is now a non-issue :)
